databases:
  - name: chatwoot-db
    plan: free
    databaseName: chatwoot_production
    user: chatwoot
    region: oregon

services:
  - type: redis
    name: chatwoot-redis
    plan: free
    ipAllowList: []

  - type: web
    name: chatwoot-web
    env: ruby
    plan: free
    repo: https://github.com/stick35em10/chatwoot
    branch: main
    buildCommand: bundle install && bundle exec rails assets:precompile && bundle exec rails db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chatwoot-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: chatwoot-redis
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: FRONTEND_URL
        value: https://chatwoot-web.onrender.com
      - key: MAILER_SENDER_EMAIL
        value: your_email@example.com
      - key: STORAGE_TYPE
        value: local

  - type: worker
    name: chatwoot-worker
    env: ruby
    plan: free
    repo: https://github.com/stick35em10/chatwoot
    branch: main
    buildCommand: bundle install
    startCommand: bundle exec sidekiq -C config/sidekiq.yml
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chatwoot-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: chatwoot-redis
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        fromService:
          type: web
          name: chatwoot-web
          envVarKey: SECRET_KEY_BASE
      - key: MAILER_SENDER_EMAIL
        value: your_email@example.com
      - key: STORAGE_TYPE
        value: local